--Item
SELECT ItemDate,
       EventDate,
       MaskedPan,
       CardToken,
       TypeName,
       FullName,
       Details,
       TrnCurrencyID,
       TrnCurrencyCode,       
       TrnAmount,       
       AccCurrencyID,
       AccCurrencyCode,       
       AccAmount,
       Rate,
       TrnFeeAmount,
       TrnFeeCurrencyID,
       TrnFeeCurrencyCode,
       ConvFeeAmount,
       ConvFeeCurrencyID,
       ConvFeeCurrencyCode,
       OpenBalance,
       TotalAmount,
       Balance,
       CloseBalance,
       MadeBy
  FROM VP_CardStmtItem